name: Publish
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # Add mkdocs plugins from Dockerfile below:
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-video
      - run: cd ./src && mkdocs gh-deploy --force
